In [1]:
import pandas as pd;
import numpy as np;

In [2]:
s = pd.Series([1,2,3,4,5,6,7])
print(s)

0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int64

In [3]:
dates = pd.date_range('20261017',periods=6)

In [4]:
df = pd.DataFrame(np.random.randn(6,4),index=dates,columns=list('ABCD'))
df

                   A         B         C         D
2026-10-17 -0.186034  0.186038  0.275271 -1.728212
2026-10-18 -1.423422 -0.218242 -1.074972 -1.075152
2026-10-19 -0.337821 -1.475204  0.521813 -0.078197
2026-10-20 -0.268783  0.303796  0.687377 -0.243785
2026-10-21 -0.095307  2.366451 -0.992343 -1.528366
2026-10-22  0.446668 -0.383778 -1.584405 -1.303523

In [5]:
df2 = pd.DataFrame(
    {
        "A": 1.0,
        "B": pd.Timestamp("20130102"),
        "C": pd.Series(1, index=list(range(4)), dtype="float32"),
        "D": np.array([3] * 4, dtype="int32"),
        "E": pd.Categorical(["test", "train", "test", "train"]),
        "F": "foo",
    }
)
df2

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [6]:
data = {'day1':30,'day2':20,'day3':15}
s1 = pd.Series(data)
print(s1.iloc[1])

20

In [7]:
data = {'name':["spongebob","patrick","squidward"],
        'age':[12,15,20]}

df = pd.DataFrame(data,index=['Emploe1','Emploe2','Emploe3'])
print(df.iloc[2])

name    squidward
age            20
Name: Emploe3, dtype: object

In [8]:
df['Job'] = ['Cook','N/A','Cashier'] #Добавление колонки
df

              name  age      Job
Emploe1  spongebob   12     Cook
Emploe2    patrick   15      N/A
Emploe3  squidward   20  Cashier

In [9]:
new_row = pd.DataFrame({"name":"Sandy","age":21,"Job":"Engineer"},index=["Emploe4"])
df = pd.concat([df,new_row])
print(df)

              name  age       Job
Emploe1  spongebob   12      Cook
Emploe2    patrick   15       N/A
Emploe3  squidward   20   Cashier
Emploe4      Sandy   21  Engineer

In [10]:
df.head(2)

              name  age   Job
Emploe1  spongebob   12  Cook
Emploe2    patrick   15   N/A

In [11]:
df.tail(3)

              name  age       Job
Emploe2    patrick   15       N/A
Emploe3  squidward   20   Cashier
Emploe4      Sandy   21  Engineer

In [12]:
df.index

Index(['Emploe1', 'Emploe2', 'Emploe3', 'Emploe4'], dtype='str')

In [13]:
df.columns

Index(['name', 'age', 'Job'], dtype='str')

In [14]:
df.to_numpy()

array([['spongebob', 12, 'Cook'],
       ['patrick', 15, 'N/A'],
       ['squidward', 20, 'Cashier'],
       ['Sandy', 21, 'Engineer']], dtype=object)

In [15]:
df.describe()

             age
count   4.000000
mean   17.000000
std     4.242641
min    12.000000
25%    14.250000
50%    17.500000
75%    20.250000
max    21.000000

In [16]:
df["age"]

Emploe1    12
Emploe2    15
Emploe3    20
Emploe4    21
Name: age, dtype: int64

In [17]:
df[["age","Job"]]

         age       Job
Emploe1   12      Cook
Emploe2   15       N/A
Emploe3   20   Cashier
Emploe4   21  Engineer

In [18]:
df[0:2] #asdfasdf

              name  age   Job
Emploe1  spongebob   12  Cook
Emploe2    patrick   15   N/A

In [19]:
df.head()

              name  age       Job
Emploe1  spongebob   12      Cook
Emploe2    patrick   15       N/A
Emploe3  squidward   20   Cashier
Emploe4      Sandy   21  Engineer